### ISSUE TITLE
Code a simple API call in Java using retrofit in anaother activity.

### ISSUE THREAD

**Issue by SuranjanDaw** [SuranjanDaw/Android-Java-Hacktoberfest-2019#2]
It can be any API. Just maintain a proper code of conduct.

**Comment by Mahesvannan** [comment]
hi i am new to hacktoberfest. I would like to work on this

**Comment by sgbcoder** [comment]
Hi Would like to understand the requirement here:
Is it to hit any API using retrofit and just populate the results in the UI?

**Comment by SuranjanDaw** [comment]
Call an API to get the data and show it on UI. But you must do using the retrofit library. @sgbcoder

**Comment by sgbcoder** [comment]
Thanks for the clarification, working on it.

**Comment by sgbcoder** [comment]
PR Link: https://github.com/SuranjanDaw/Android-Java-Hacktoberfest-2019/pull/6

**Comment by im-ranu** [comment]
I also want to contribute

**Comment by im-ranu** [comment]
Forked repo and created branch just adding api call using retrofit

**Comment by sgbcoder** [comment]
since i have raised a PR for creating the retrofit call,you could maybe help in enhancing the way the data is populated using a recyclerView.Right now i am just showing the first post title and body, it will look really nice if a recyclerview is added.You could help me with that.

**Comment by im-ranu** [comment]
But I added retrofit call and showing images into GridView 
refer PR : #8 

I will also help you to enhacing UI and will add recyclerview.

**Comment by SuranjanDaw** [comment]
Great Work team. Thank you all for your contributions.
